version: '{branch}.{build}'
skip_tags: true

image:
- Visual Studio 2019
- macos

matrix:
  exclude:
    - platform: x86
      image: macOS

platform:
  - x64
  - x86
  
configuration: Release

branches:
  only:
    - main

build:
  verbosity: detailed

environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(PLATFORM)
  buildConfig: $(CONFIGURATION)
  buildPlatform: $(PLATFORM)

for:
  -
    matrix:
      only:
        - image: macOS

    
    install:
     - git submodule update --init --recursive
     - export PATH="$HOME/Qt/5.15.2/clang_64/bin:$PATH"
     - export LDFLAGS="-L/usr/local/opt/qt/lib"
     - export CPPFLAGS="-I/usr/local/opt/qt/include"
     - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

    before_build:
      - cmake --version
      - qmake -v

    build_script:
      - ./macos_wrap.sh macdeployqt

    after_build:
       - ls

    artifacts:
       - path: PE-bear.app.zip
       
  -
    matrix:
      only:
        - image: Visual Studio 2019
    
    install:
     - git submodule update --init --recursive
     - if [%buildPlatform%]==[x64] (
       set QT=C:\Qt\6.7.0\msvc2019_64)
     - if [%buildPlatform%]==[x86] (
       set QT=C:\Qt\6.7.0\msvc2019)
     - set PATH=%PATH%;%QT%\bin;%QT%\lib\cmake
     - set Qt6Core_DIR=%QT%
     
    before_build:
     - mkdir build
     - cd build
     
    build_script:
      - if [%buildPlatform%]==[x64] (
        cmake .. -A x64 -DCOMMIT_HASH:STRING="\""%APPVEYOR_REPO_COMMIT%"\"" )
      - if [%buildPlatform%]==[x86] (
        cmake .. -A Win32 -DCOMMIT_HASH:STRING="\""%APPVEYOR_REPO_COMMIT%"\"" )
      - cmake --build . --config %buildConfig%

    after_build:
     - mkdir %artifactName%
     - dir -r "%QT%"
     - cp -r pe-bear/%buildConfig%/* %artifactName%
     - cp "%QT%\bin\*.dll" %artifactName%
     - mkdir %artifactName%\platforms
     - mkdir %artifactName%\styles
     - mkdir %artifactName%\imageformats
     - cp "%QT%\plugins\platforms\qwindows.dll" %artifactName%\platforms
     - cp "%QT%\plugins\styles\qwindowsvistastyle.dll" %artifactName%\styles
     - cp "%QT%\plugins\imageformats\qico.dll" %artifactName%\imageformats

    artifacts:
     - path: build\%artifactName%
     
